# Brazilian E-Commerce Analysis

![alt text](https://i.imgur.com/HRhd2Y0.png)

## Data Cleaning

In [1]:
import pandas as pd
import numpy as np

In [2]:
olist_sellers_dataset = pd.read_csv("../data/olist_sellers_dataset.csv")
product_category_name_translation = pd.read_csv("../data/product_category_name_translation.csv")
olist_orders_dataset = pd.read_csv("../data/olist_orders_dataset.csv")
olist_order_items_dataset = pd.read_csv("../data/olist_order_items_dataset.csv")
olist_customers_dataset = pd.read_csv("../data/olist_customers_dataset.csv")
olist_geolocation_dataset = pd.read_csv("../data/olist_geolocation_dataset.csv")
olist_order_payments_dataset = pd.read_csv("../data/olist_order_payments_dataset.csv")
olist_order_reviews_dataset = pd.read_csv("../data/olist_order_reviews_dataset.csv")
olist_products_dataset = pd.read_csv("../data/olist_products_dataset.csv")

In [3]:

df = olist_orders_dataset.copy()

#  Orders + Customers
df = df.merge(
    olist_customers_dataset,
    on="customer_id",
    how="left"
)

# df + Order Items
df = df.merge(
    olist_order_items_dataset,
    on="order_id",
    how="left"
)

# df + Products
df = df.merge(
    olist_products_dataset,
    on="product_id",
    how="left"
)

# df + Sellers
df = df.merge(
    olist_sellers_dataset,
    on="seller_id",
    how="left"
)

# df  + Payments
df = df.merge(
    olist_order_payments_dataset,
    on="order_id",
    how="left"
)

# df + Reviews
df = df.merge(
    olist_order_reviews_dataset,
    on="order_id",
    how="left"
)

# df + Product Category Translation
df = df.merge(
    product_category_name_translation,
    on="product_category_name",
    how="left"
)

# 8. Handle Geolocation
geo = olist_geolocation_dataset.groupby("geolocation_zip_code_prefix").agg({
    "geolocation_lat": "mean",
    "geolocation_lng": "mean"
}).reset_index()

# Merge geolocation
df = df.merge(
    geo,
    left_on="customer_zip_code_prefix",
    right_on="geolocation_zip_code_prefix",
    how="left"
)
df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,product_category_name_english,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,a54f0611adc9ed256b57ede6b6eb5114,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48,housewares,3149.0,-23.576983,-46.587161
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,a54f0611adc9ed256b57ede6b6eb5114,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48,housewares,3149.0,-23.576983,-46.587161
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,a54f0611adc9ed256b57ede6b6eb5114,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48,housewares,3149.0,-23.576983,-46.587161
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,...,8d5266042046a06655c8db133d120ba5,4.0,Muito boa a loja,Muito bom o produto.,2018-08-08 00:00:00,2018-08-08 18:37:50,perfumery,47813.0,-12.177924,-44.660711
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,e73b67b67587f7644d5bd1a52deb1b01,5.0,NaN,NaN,2018-08-18 00:00:00,2018-08-22 19:07:58,auto,75265.0,-16.745150,-48.514783

## Data Shape

In [4]:
print("Shape:", df.shape)

Shape: (119143, 43)

In [5]:
print("\nColumn names:")
print(df.columns.tolist())

Column names:
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm', 'seller_zip_code_prefix', 'seller_city', 'seller_state', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value', 'review_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp', 'product_category_name_english', 'geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng']

In [6]:
print("\nBasic info:")
print(df.info())

Basic info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119143 entries, 0 to 119142
Data columns (total 43 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       119143 non-null  object
 1   customer_id                    119143 non-null  object
 2   order_status                   119143 non-null  object
 3   order_purchase_timestamp       119143 non-null  object
 4   order_approved_at              118966 non-null  object
 5   order_delivered_carrier_date   117057 non-null  object
 6   order_delivered_customer_date  115722 non-null  object
 7   order_estimated_delivery_date  119143 non-null  object
 8   customer_unique_id             119143 non-null  object
 9   customer_zip_code_prefix       119143 non-null  int64
 10  customer_city                  119143 non-null  object
 11  customer_state                 119143 non-null  object
 12  order_item_id                  118310 non-null  float64
 13  product_id                     118310 non-null  object
 14  seller_id                      118310 non-null  object
 15  shipping_limit_date            118310 non-null  object
 16  price                          118310 non-null  float64
 17  freight_value                  118310 non-null  float64
 18  product_category_name          116601 non-null  object
 19  product_name_lenght            116601 non-null  float64
 20  product_description_lenght     116601 non-null  float64
 21  product_photos_qty             116601 non-null  float64
 22  product_weight_g               118290 non-null  float64
 23  product_length_cm              118290 non-null  float64
 24  product_height_cm              118290 non-null  float64
 25  product_width_cm               118290 non-null  float64
 26  seller_zip_code_prefix         118310 non-null  float64
 27  seller_city                    118310 non-null  object
 28  seller_state                   118310 non-null  object
 29  payment_sequential             119140 non-null  float64
 30  payment_type                   119140 non-null  object
 31  payment_installments           119140 non-null  float64
 32  payment_value                  119140 non-null  float64
 33  review_id                      118146 non-null  object
 34  review_score                   118146 non-null  float64
 35  review_comment_title           13989 non-null   object
 36  review_comment_message         50245 non-null   object
 37  review_creation_date           118146 non-null  object
 38  review_answer_timestamp        118146 non-null  object
 39  product_category_name_english  116576 non-null  object
 40  geolocation_zip_code_prefix    118821 non-null  float64
 41  geolocation_lat                118821 non-null  float64
 42  geolocation_lng                118821 non-null  float64
dtypes: float64(18), int64(1), object(24)
memory usage: 39.1+ MB
None

In [7]:
# 1) Convert datetime columns
datetime_cols = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date",
    "shipping_limit_date",
    "review_creation_date",
    "review_answer_timestamp",
]

for col in datetime_cols:
    df[col] = pd.to_datetime(df[col], errors="coerce")

# 2) Convert integer-like columns with missing values to nullable integer type
nullable_int_cols = [
    "customer_zip_code_prefix",
    "order_item_id",
    "product_name_lenght",
    "product_description_lenght",
    "product_photos_qty",
    "seller_zip_code_prefix",
    "payment_sequential",
    "payment_installments",
    "review_score",
    "geolocation_zip_code_prefix",
]

for col in nullable_int_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce").astype("Int64")

# 3) Convert true numeric columns to float
float_cols = [
    "price",
    "freight_value",
    "payment_value",
    "product_weight_g",
    "product_length_cm",
    "product_height_cm",
    "product_width_cm",
    "geolocation_lat",
    "geolocation_lng",
]

for col in float_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# 4) Convert text columns to pandas string dtype
string_cols = [
    "order_id",
    "customer_id",
    "order_status",
    "customer_unique_id",
    "customer_city",
    "customer_state",
    "product_id",
    "seller_id",
    "product_category_name",
    "seller_city",
    "seller_state",
    "payment_type",
    "review_id",
    "review_comment_title",
    "review_comment_message",
    "product_category_name_english",
]

for col in string_cols:
    df[col] = df[col].astype("string")

# 5) Optional: make low-cardinality text columns categorical to save memory
category_cols = [
    "order_status",
    "customer_state",
    "seller_state",
    "payment_type",
    "product_category_name",
    "product_category_name_english",
]

for col in category_cols:
    df[col] = df[col].astype("category")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119143 entries, 0 to 119142
Data columns (total 43 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       119143 non-null  string
 1   customer_id                    119143 non-null  string
 2   order_status                   119143 non-null  category
 3   order_purchase_timestamp       119143 non-null  datetime64[ns]
 4   order_approved_at              118966 non-null  datetime64[ns]
 5   order_delivered_carrier_date   117057 non-null  datetime64[ns]
 6   order_delivered_customer_date  115722 non-null  datetime64[ns]
 7   order_estimated_delivery_date  119143 non-null  datetime64[ns]
 8   customer_unique_id             119143 non-null  string
 9   customer_zip_code_prefix       119143 non-null  Int64
 10  customer_city                  119143 non-null  string
 11  customer_state                 119143 non-null  category
 12  order_item_id                  118310 non-null  Int64
 13  product_id                     118310 non-null  string
 14  seller_id                      118310 non-null  string
 15  shipping_limit_date            118310 non-null  datetime64[ns]
 16  price                          118310 non-null  float64
 17  freight_value                  118310 non-null  float64
 18  product_category_name          116601 non-null  category
 19  product_name_lenght            116601 non-null  Int64
 20  product_description_lenght     116601 non-null  Int64
 21  product_photos_qty             116601 non-null  Int64
 22  product_weight_g               118290 non-null  float64
 23  product_length_cm              118290 non-null  float64
 24  product_height_cm              118290 non-null  float64
 25  product_width_cm               118290 non-null  float64
 26  seller_zip_code_prefix         118310 non-null  Int64
 27  seller_city                    118310 non-null  string
 28  seller_state                   118310 non-null  category
 29  payment_sequential             119140 non-null  Int64
 30  payment_type                   119140 non-null  category
 31  payment_installments           119140 non-null  Int64
 32  payment_value                  119140 non-null  float64
 33  review_id                      118146 non-null  string
 34  review_score                   118146 non-null  Int64
 35  review_comment_title           13989 non-null   string
 36  review_comment_message         50245 non-null   string
 37  review_creation_date           118146 non-null  datetime64[ns]
 38  review_answer_timestamp        118146 non-null  datetime64[ns]
 39  product_category_name_english  116576 non-null  category
 40  geolocation_zip_code_prefix    118821 non-null  Int64
 41  geolocation_lat                118821 non-null  float64
 42  geolocation_lng                118821 non-null  float64
dtypes: Int64(10), category(6), datetime64[ns](8), float64(9), string(10)
memory usage: 35.5 MB

In [8]:
## integer statistics
df.describe(include='int')

,customer_zip_code_prefix,order_item_id,product_name_lenght,product_description_lenght,product_photos_qty,seller_zip_code_prefix,payment_sequential,payment_installments,review_score,geolocation_zip_code_prefix
count,119143.0,118310.0,116601.0,116601.0,116601.0,118310.0,119140.0,119140.0,118146.0,118821.0
mean,35033.451298,1.196543,48.767498,785.967822,2.205161,24442.410413,1.094737,2.941246,4.015582,34955.424125
std,29823.198969,0.699489,10.03354,652.584121,1.717452,27573.004511,0.730141,2.777848,1.400436,29809.673053
min,1003.0,1.0,5.0,4.0,1.0,1001.0,1.0,0.0,1.0,1003.0
25%,11250.0,1.0,42.0,346.0,1.0,6429.0,1.0,1.0,4.0,11089.0
50%,24240.0,1.0,52.0,600.0,1.0,13660.0,1.0,2.0,5.0,24230.0
75%,58475.0,1.0,57.0,983.0,3.0,27972.0,1.0,4.0,5.0,58187.0
max,99990.0,21.0,76.0,3992.0,20.0,99730.0,29.0,24.0,5.0,99990.0

In [9]:
## category statistics
df.describe(include='category')

,order_status,customer_state,product_category_name,seller_state,payment_type,product_category_name_english
count,119143,119143,116601,118310,119140,116576
unique,8,27,73,23,5,71
top,delivered,SP,cama_mesa_banho,SP,credit_card,bed_bath_table
freq,115723,50265,11988,84377,87776,11988

In [10]:
# Replace common missing value symbols with NaN
df.replace(["", " ", "NA", "N/A", "NULL", "null", "-", "--"], np.nan, inplace=True)

print("\nMissing percentage per column:")

missing_percent = (df.isnull().sum() / len(df)) * 100
print(missing_percent.round(3))

Missing percentage per column:
order_id                          0.000
customer_id                       0.000
order_status                      0.000
order_purchase_timestamp          0.000
order_approved_at                 0.149
order_delivered_carrier_date      1.751
order_delivered_customer_date     2.871
order_estimated_delivery_date     0.000
customer_unique_id                0.000
customer_zip_code_prefix          0.000
customer_city                     0.000
customer_state                    0.000
order_item_id                     0.699
product_id                        0.699
seller_id                         0.699
shipping_limit_date               0.699
price                             0.699
freight_value                     0.699
product_category_name             2.134
product_name_lenght               2.134
product_description_lenght        2.134
product_photos_qty                2.134
product_weight_g                  0.716
product_length_cm                 0.716
product_height_cm                 0.716
product_width_cm                  0.716
seller_zip_code_prefix            0.699
seller_city                       0.699
seller_state                      0.699
payment_sequential                0.003
payment_type                      0.003
payment_installments              0.003
payment_value                     0.003
review_id                         0.837
review_score                      0.837
review_comment_title             88.261
review_comment_message           57.840
review_creation_date              0.837
review_answer_timestamp           0.837
product_category_name_english     2.155
geolocation_zip_code_prefix       0.270
geolocation_lat                   0.270
geolocation_lng                   0.270
dtype: float64

Insights
1. Most columns have ~0% missing, indicating the dataset is clean and reliable.
2. Delivery-related columns (1–3% missing) likely reflect cancelled or undelivered orders rather than data issues.
3. Product-related fields (~2% missing) suggest some products have incomplete information.
4. Order item and seller fields (~0.7% missing) show minor inconsistencies with low impact.
5. Review text fields are highly missing (title ~88%, message ~58%), meaning most users provide ratings but not written feedback.
6. Geolocation data (~0.27% missing) has negligible impact.<br>
Overall, the dataset quality is high, and most missing values represent real-world behavior rather than errors.

In [11]:
# Drop high-missing columns
df1 = df.copy()
high_missing_cols = [
    'review_comment_title',
    'review_comment_message'
]

df1.drop(columns=high_missing_cols, inplace=True)

In [12]:
df1.dropna(subset=[
    'product_id',
    'seller_id'
], inplace=True)

In [13]:
# Fill numeric columns with median
num_cols = df1.select_dtypes(include=['float64', 'int64']).columns

for col in num_cols:
    df1[col]=df1[col].fillna(df1[col].median())

In [14]:
#  Fill categorical columns with mode
cat_cols = df1.select_dtypes(include=['object']).columns

for col in cat_cols:
    df1[col].fillna(df1[col].mode()[0], inplace=True)

In [15]:

missing_percent = (df1.isnull().sum() / len(df1)) * 100
print(missing_percent.round(3))

order_id                         0.000
customer_id                      0.000
order_status                     0.000
order_purchase_timestamp         0.000
order_approved_at                0.013
order_delivered_carrier_date     1.060
order_delivered_customer_date    2.187
order_estimated_delivery_date    0.000
customer_unique_id               0.000
customer_zip_code_prefix         0.000
customer_city                    0.000
customer_state                   0.000
order_item_id                    0.000
product_id                       0.000
seller_id                        0.000
shipping_limit_date              0.000
price                            0.000
freight_value                    0.000
product_category_name            1.445
product_name_lenght              0.000
product_description_lenght       0.000
product_photos_qty               0.000
product_weight_g                 0.000
product_length_cm                0.000
product_height_cm                0.000
product_width_cm                 0.000
seller_zip_code_prefix           0.000
seller_city                      0.000
seller_state                     0.000
payment_sequential               0.000
payment_type                     0.003
payment_installments             0.000
payment_value                    0.000
review_id                        0.827
review_score                     0.000
review_creation_date             0.827
review_answer_timestamp          0.827
product_category_name_english    1.466
geolocation_zip_code_prefix      0.000
geolocation_lat                  0.000
geolocation_lng                  0.000
dtype: float64

In [16]:
df1.dropna(inplace=True)

In [17]:
# check duplicate
print("\nDuplicate rows:", df1.duplicated().sum())

Duplicate rows: 0

In [18]:
# Remove leading/trailing spaces from all text columns
for col in df1.select_dtypes(include="object").columns:
    df1[col] = df1[col].str.strip()

In [19]:
# Convert text columns to lowercase 
for col in df1.select_dtypes(include="object").columns:
    df1[col] = df1[col].str.lower()

In [20]:
# Remove negative values from columns that should not be negative
possible_positive_cols = ["age", "salary", "price", "quantity"]

for col in possible_positive_cols:
    if col in df1.columns:
        df1 = df1[df1[col] >= 0]

In [21]:
# Purchase <= Approved
df1 = df1[
    (df1['order_purchase_timestamp'] <= df1['order_approved_at']) |
    (df1['order_approved_at'].isna())
]

#  Approved <= Carrier
df1 = df1[
    (df1['order_approved_at'] <= df1['order_delivered_carrier_date']) |
    (df1['order_delivered_carrier_date'].isna())
]

#  Carrier <= Customer Delivered
df1 = df1[
    (df1['order_delivered_carrier_date'] <= df1['order_delivered_customer_date']) |
    (df1['order_delivered_customer_date'].isna())
]

In [24]:

missing_percent = (df1.isnull().sum() / len(df1)) * 100
print(missing_percent.round(3))

order_id                         0.0
customer_id                      0.0
order_status                     0.0
order_purchase_timestamp         0.0
order_approved_at                0.0
order_delivered_carrier_date     0.0
order_delivered_customer_date    0.0
order_estimated_delivery_date    0.0
customer_unique_id               0.0
customer_zip_code_prefix         0.0
customer_city                    0.0
customer_state                   0.0
order_item_id                    0.0
product_id                       0.0
seller_id                        0.0
shipping_limit_date              0.0
price                            0.0
freight_value                    0.0
product_category_name            0.0
product_name_lenght              0.0
product_description_lenght       0.0
product_photos_qty               0.0
product_weight_g                 0.0
product_length_cm                0.0
product_height_cm                0.0
product_width_cm                 0.0
seller_zip_code_prefix           0.0
seller_city                      0.0
seller_state                     0.0
payment_sequential               0.0
payment_type                     0.0
payment_installments             0.0
payment_value                    0.0
review_id                        0.0
review_score                     0.0
review_creation_date             0.0
review_answer_timestamp          0.0
product_category_name_english    0.0
geolocation_zip_code_prefix      0.0
geolocation_lat                  0.0
geolocation_lng                  0.0
dtype: float64